version: "3"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-java-examples
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
